/**
 * Application Bootstrap File
 * 
 * This is the entry point for the Angular application. It:
 * 1. Configures AWS Amplify with backend settings
 * 2. Bootstraps the main Angular application
 * 3. Sets up error handling for the bootstrap process
 * 
 * This file runs when the application starts and initializes
 * all the necessary services and configurations.
 */

import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { AppComponent } from './app/app.component';

// AWS Amplify imports
import { Amplify } from 'aws-amplify';
import outputs from '../amplify_outputs.json';

/**
 * Configure AWS Amplify
 * 
 * This connects the frontend application to the AWS backend services.
 * The amplify_outputs.json file contains all the configuration generated
 * by the Amplify CLI, including:
 * - Authentication settings (Cognito User Pool)
 * - API endpoints (GraphQL/REST APIs)
 * - Storage configurations (S3 buckets)
 * - Other AWS service configurations
 * 
 * This file is automatically generated when you run:
 * npx ampx generate outputs
 */
Amplify.configure(outputs);

/**
 * Bootstrap the Angular Application
 * 
 * This starts the Angular application with the specified configuration
 * and mounts the root AppComponent to the DOM.
 * 
 * The appConfig contains:
 * - Router configuration
 * - Service providers
 * - Other application-wide settings
 */
bootstrapApplication(AppComponent, appConfig)
  .catch((err) => {
    // Log any errors that occur during application startup
    console.error('Failed to bootstrap application:', err);
  });